on:
  issue_comment:
    types: [ created ]
name: Pull requests comment
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: PullRequestHandler
      uses: Ash258/Scoop-GithubActions@main-win
      if: startsWith(github.event.comment.body, '/verify') && contains(["Ash258"], github.event.comment.user.login)
      env:
        GITH_EMAIL: youremail@mail.com # Not needed, but recommended
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHOVEL: '1'
