on:
  issue_comment:
    types: [ created ]
name: Pull requests comment
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: PullRequestHandler
      uses: shovel-org/GithubActions@dev
      if: startsWith(github.event.comment.body, '/verify') && contains(fromJSON('["Ash258", "CosiTemporaryTest"]'), github.event.comment.user.login)
      env:
        GITH_EMAIL: youremail@mail.com # Not needed, but recommended
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
