on:
  schedule:
  - cron: '0 0/12 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@master-win
      env:
        GITH_EMAIL: cabera.jakub@gmail.com
        GITHUB_TOKEN: ${{ secrets.GITH_TOKE_ASH258 }}
        SKIP_UPDATED: '1'
        SHOVEL: '1'
