on:
  schedule:
  - cron: '*/10 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@excavatorTest
      env:
        GITH_EMAIL: cabera.jakub@gmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_ASH258 }}
        SKIP_UPDATED: '1'
