on:
  schedules:
  - cron: '*/10 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@master
      env:
        GITH_EMAIL: cabera.jakub@gmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_PUB: ${{ secrets.SSH_PUB }}
        SKIP_UPDATED: '1'
