on:
  workflow_dispatch:
  schedule:
  - cron: '0 0/6 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@main-win
      env:
        GITH_EMAIL: cabera.jakub@gmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
        SHOVEL: '1'
        TERM: xterm-256color
        SCOOP_BRANCH: installOld
